/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.AuditLogController;

/**
 *
 * @author ASUS
 */
public class AuditLogForm extends javax.swing.JPanel {

    private AuditLogController controller;

    /**
     * Creates new form AuditLogForm
     */
    public AuditLogForm() {
        initComponents();
        controller = new AuditLogController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        // --- TOP PANEL ---
        javax.swing.JPanel pnlTop = new javax.swing.JPanel();
        
        javax.swing.JLabel lblTitle = new javax.swing.JLabel("📋 NHẬT KÝ HOẠT ĐỘNG HỆ THỐNG");
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20));
        lblTitle.setForeground(new java.awt.Color(52, 73, 94));
        
        javax.swing.JLabel lblInfo = new javax.swing.JLabel("Theo dõi các thao tác thêm/sửa/xóa trong hệ thống");
        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 13));
        lblInfo.setForeground(new java.awt.Color(127, 140, 141));
        
        // --- FILTER PANEL ---
        javax.swing.JPanel pnlFilter = new javax.swing.JPanel();
        
        javax.swing.JLabel lblUser = new javax.swing.JLabel("Người dùng:");
        cboUser = new javax.swing.JComboBox<>();
        cboUser.addItem("-- Tất cả --");
        
        javax.swing.JLabel lblAction = new javax.swing.JLabel("Hành động:");
        cboAction = new javax.swing.JComboBox<>();
        cboAction.addItem("-- Tất cả --");
        cboAction.addItem("INSERT");
        cboAction.addItem("UPDATE");
        cboAction.addItem("DELETE");
        cboAction.addItem("LOGIN");
        cboAction.addItem("LOGOUT");
        
        javax.swing.JLabel lblTable = new javax.swing.JLabel("Bảng:");
        cboTable = new javax.swing.JComboBox<>();
        cboTable.addItem("-- Tất cả --");
        cboTable.addItem("DauSach");
        cboTable.addItem("CuonSach");
        cboTable.addItem("DocGia");
        cboTable.addItem("PhieuMuon");
        cboTable.addItem("PhieuPhat");
        cboTable.addItem("NguoiDung");
        
        btnFilter = new javax.swing.JButton("🔍 Lọc");
        btnFilter.setBackground(new java.awt.Color(52, 152, 219));
        btnFilter.setForeground(java.awt.Color.WHITE);
        btnFilter.setFont(new java.awt.Font("Segoe UI", 1, 12));
        
        btnRefresh = new javax.swing.JButton("🔄 Làm mới");
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12));
        
        // --- TABLE ---
        javax.swing.JScrollPane scrollTable = new javax.swing.JScrollPane();
        tblAuditLog = new javax.swing.JTable();
        tblAuditLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "ID", "Người dùng", "Hành động", "Bảng", "Mã bản ghi", "Mô tả", "IP", "Thời gian" }
        ) {
            boolean[] canEdit = new boolean [] { false, false, false, false, false, false, false, false };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAuditLog.setRowHeight(28);
        tblAuditLog.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAuditLog.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 12));
        tblAuditLog.getTableHeader().setReorderingAllowed(false);
        scrollTable.setViewportView(tblAuditLog);
        
        // Column widths
        tblAuditLog.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblAuditLog.getColumnModel().getColumn(0).setMaxWidth(70);
        tblAuditLog.getColumnModel().getColumn(1).setPreferredWidth(120);
        tblAuditLog.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblAuditLog.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblAuditLog.getColumnModel().getColumn(4).setPreferredWidth(80);
        tblAuditLog.getColumnModel().getColumn(5).setPreferredWidth(300);
        tblAuditLog.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblAuditLog.getColumnModel().getColumn(7).setPreferredWidth(150);
        
        // --- LAYOUT ---
        setLayout(new java.awt.BorderLayout(10, 10));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        
        // TOP PANEL
        pnlTop.setLayout(new java.awt.GridBagLayout());
        pnlTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlTop.add(lblTitle, gridBagConstraints);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlTop.add(lblInfo, gridBagConstraints);
        
        add(pnlTop, java.awt.BorderLayout.NORTH);
        
        // FILTER PANEL
        pnlFilter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 10));
        pnlFilter.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createTitledBorder(null, "Bộ lọc", 
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
                javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                new java.awt.Font("Segoe UI", 1, 13)),
            javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
        
        pnlFilter.add(lblUser);
        cboUser.setPreferredSize(new java.awt.Dimension(150, 30));
        pnlFilter.add(cboUser);
        
        pnlFilter.add(lblAction);
        cboAction.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlFilter.add(cboAction);
        
        pnlFilter.add(lblTable);
        cboTable.setPreferredSize(new java.awt.Dimension(120, 30));
        pnlFilter.add(cboTable);
        
        pnlFilter.add(btnFilter);
        pnlFilter.add(btnRefresh);
        
        // CENTER PANEL
        javax.swing.JPanel pnlCenter = new javax.swing.JPanel(new java.awt.BorderLayout(0, 10));
        pnlCenter.add(pnlFilter, java.awt.BorderLayout.NORTH);
        pnlCenter.add(scrollTable, java.awt.BorderLayout.CENTER);
        
        add(pnlCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cboAction;
    private javax.swing.JComboBox<String> cboTable;
    private javax.swing.JComboBox<String> cboUser;
    private javax.swing.JTable tblAuditLog;
    // End Variables

    // Getters
    public javax.swing.JButton getBtnFilter() { return btnFilter; }
    public javax.swing.JButton getBtnRefresh() { return btnRefresh; }
    public javax.swing.JComboBox<String> getCboAction() { return cboAction; }
    public javax.swing.JComboBox<String> getCboTable() { return cboTable; }
    public javax.swing.JComboBox<String> getCboUser() { return cboUser; }
    public javax.swing.JTable getTblAuditLog() { return tblAuditLog; }
}
