/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.CategoryController;

/**
 *
 * @author ASUS
 */
public class CategoryForm extends javax.swing.JPanel {

    private CategoryController controller;

    /**
     * Creates new form CategoryForm
     */
    public CategoryForm() {
        initComponents();
        controller = new CategoryController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JPanel pnlInput = new javax.swing.JPanel();
        javax.swing.JPanel pnlList = new javax.swing.JPanel();
        
        // --- INPUT PANEL COMPONENTS ---
        javax.swing.JLabel lblTitle = new javax.swing.JLabel("QUẢN LÝ THỂ LOẠI SÁCH");
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18));
        lblTitle.setForeground(new java.awt.Color(52, 73, 94));
        
        javax.swing.JLabel lblMaTheLoai = new javax.swing.JLabel("Mã thể loại:");
        txtMaTheLoai = new javax.swing.JTextField();
        txtMaTheLoai.setEditable(false);
        txtMaTheLoai.setBackground(new java.awt.Color(240, 240, 240));
        
        javax.swing.JLabel lblTenTheLoai = new javax.swing.JLabel("Tên thể loại:");
        txtTenTheLoai = new javax.swing.JTextField();
        
        javax.swing.JLabel lblMoTa = new javax.swing.JLabel("Mô tả:");
        javax.swing.JScrollPane scrollMoTa = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        txtMoTa.setRows(3);
        txtMoTa.setLineWrap(true);
        txtMoTa.setWrapStyleWord(true);
        scrollMoTa.setViewportView(txtMoTa);
        
        // Buttons
        javax.swing.JPanel pnlButtons = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton("➕ Thêm");
        btnEdit = new javax.swing.JButton("✏️ Sửa");
        btnDelete = new javax.swing.JButton("🗑️ Xóa");
        btnReset = new javax.swing.JButton("🔄 Làm mới");
        
        btnAdd.setBackground(new java.awt.Color(46, 204, 113));
        btnAdd.setForeground(java.awt.Color.WHITE);
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12));
        
        btnEdit.setBackground(new java.awt.Color(52, 152, 219));
        btnEdit.setForeground(java.awt.Color.WHITE);
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12));
        
        btnDelete.setBackground(new java.awt.Color(231, 76, 60));
        btnDelete.setForeground(java.awt.Color.WHITE);
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12));
        
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12));
        
        // --- TABLE ---
        javax.swing.JScrollPane scrollTable = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Mã", "Tên Thể Loại", "Mô Tả" }
        ) {
            boolean[] canEdit = new boolean [] { false, false, false };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCategory.setRowHeight(30);
        tblCategory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCategory.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 13));
        tblCategory.getTableHeader().setReorderingAllowed(false);
        scrollTable.setViewportView(tblCategory);
        
        // Column widths
        tblCategory.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblCategory.getColumnModel().getColumn(0).setMaxWidth(100);
        tblCategory.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblCategory.getColumnModel().getColumn(2).setPreferredWidth(400);

        // --- LAYOUT ---
        setLayout(new java.awt.BorderLayout(15, 15));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        
        // INPUT PANEL LAYOUT
        pnlInput.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createTitledBorder(null, "Thông tin thể loại", 
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
                javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                new java.awt.Font("Segoe UI", 1, 14)),
            javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        pnlInput.setLayout(new java.awt.GridBagLayout());
        pnlInput.setPreferredSize(new java.awt.Dimension(400, 0));
        
        // Row 0: Title
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlInput.add(lblTitle, gridBagConstraints);
        
        // Row 1: Mã
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        pnlInput.add(lblMaTheLoai, gridBagConstraints);
        
        txtMaTheLoai.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnlInput.add(txtMaTheLoai, gridBagConstraints);
        
        // Row 2: Tên
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        pnlInput.add(lblTenTheLoai, gridBagConstraints);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnlInput.add(txtTenTheLoai, gridBagConstraints);
        
        // Row 3: Mô tả
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        pnlInput.add(lblMoTa, gridBagConstraints);
        
        scrollMoTa.setPreferredSize(new java.awt.Dimension(250, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnlInput.add(scrollMoTa, gridBagConstraints);
        
        // Row 4: Buttons
        pnlButtons.setLayout(new java.awt.GridLayout(2, 2, 10, 10));
        pnlButtons.add(btnAdd);
        pnlButtons.add(btnEdit);
        pnlButtons.add(btnDelete);
        pnlButtons.add(btnReset);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        pnlInput.add(pnlButtons, gridBagConstraints);
        
        add(pnlInput, java.awt.BorderLayout.WEST);
        
        // LIST PANEL
        pnlList.setLayout(new java.awt.BorderLayout(5, 5));
        pnlList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách thể loại", 
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
            javax.swing.border.TitledBorder.DEFAULT_POSITION, 
            new java.awt.Font("Segoe UI", 1, 14)));
        pnlList.add(scrollTable, java.awt.BorderLayout.CENTER);
        
        add(pnlList, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTextField txtMaTheLoai;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenTheLoai;
    // End Variables

    // Getters
    public javax.swing.JButton getBtnAdd() { return btnAdd; }
    public javax.swing.JButton getBtnDelete() { return btnDelete; }
    public javax.swing.JButton getBtnEdit() { return btnEdit; }
    public javax.swing.JButton getBtnReset() { return btnReset; }
    public javax.swing.JTable getTblCategory() { return tblCategory; }
    public javax.swing.JTextField getTxtMaTheLoai() { return txtMaTheLoai; }
    public javax.swing.JTextArea getTxtMoTa() { return txtMoTa; }
    public javax.swing.JTextField getTxtTenTheLoai() { return txtTenTheLoai; }
}
