/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.HomeController;

/**
 *
 * @author ASUS
 */
public class HomeForm extends javax.swing.JPanel {

    private HomeController controller;

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
        controller = new HomeController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        
        // --- TOP WELCOME PANEL ---
        javax.swing.JPanel pnlWelcome = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        
        // --- STATS PANEL ---
        javax.swing.JPanel pnlStats = new javax.swing.JPanel();
        
        // Stat Cards
        javax.swing.JPanel pnlCard1 = createStatCard("📚 SÁCH QUÁ HẠN", new java.awt.Color(231, 76, 60));
        lblOverdueCount = new javax.swing.JLabel("0");
        
        javax.swing.JPanel pnlCard2 = createStatCard("⚠️ SẮP HẾT HẠN", new java.awt.Color(241, 196, 15));
        lblDueSoonCount = new javax.swing.JLabel("0");
        
        javax.swing.JPanel pnlCard3 = createStatCard("📖 ĐANG MƯỢN", new java.awt.Color(52, 152, 219));
        lblBorrowingCount = new javax.swing.JLabel("0");
        
        javax.swing.JPanel pnlCard4 = createStatCard("💰 PHẠT CHƯA ĐÃ", new java.awt.Color(155, 89, 182));
        lblUnpaidPenalty = new javax.swing.JLabel("0đ");
        
        // Add labels to cards
        styleValueLabel(lblOverdueCount); pnlCard1.add(lblOverdueCount);
        styleValueLabel(lblDueSoonCount); pnlCard2.add(lblDueSoonCount);
        styleValueLabel(lblBorrowingCount); pnlCard3.add(lblBorrowingCount);
        styleValueLabel(lblUnpaidPenalty); pnlCard4.add(lblUnpaidPenalty);
        
        // --- TABLES PANEL ---
        javax.swing.JTabbedPane tabbedPane = new javax.swing.JTabbedPane();
        
        // Tab 1: Overdue Books
        javax.swing.JPanel pnlOverdue = new javax.swing.JPanel();
        pnlOverdue.setLayout(new java.awt.BorderLayout(5, 5));
        
        javax.swing.JScrollPane scrollOverdue = new javax.swing.JScrollPane();
        tblOverdue = new javax.swing.JTable();
        tblOverdue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Mã Thẻ", "Tên Độc Giả", "SĐT", "Email", "Tên Sách", "Hạn Trả", "Quá Hạn (ngày)" }
        ) {
            boolean[] canEdit = new boolean [] { false, false, false, false, false, false, false };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOverdue.setRowHeight(25);
        tblOverdue.getTableHeader().setReorderingAllowed(false);
        scrollOverdue.setViewportView(tblOverdue);
        
        btnCallOverdue = new javax.swing.JButton("📞 Liên hệ độc giả");
        btnCallOverdue.setBackground(new java.awt.Color(231, 76, 60));
        btnCallOverdue.setForeground(java.awt.Color.WHITE);
        btnCallOverdue.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnCallOverdue.setFocusPainted(false);
        
        javax.swing.JPanel pnlOverdueBtn = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pnlOverdueBtn.add(btnCallOverdue);
        
        pnlOverdue.add(scrollOverdue, java.awt.BorderLayout.CENTER);
        pnlOverdue.add(pnlOverdueBtn, java.awt.BorderLayout.SOUTH);
        
        tabbedPane.addTab("🔴 Sách Quá Hạn", pnlOverdue);
        
        // Tab 2: Due Soon Books
        javax.swing.JPanel pnlDueSoon = new javax.swing.JPanel();
        pnlDueSoon.setLayout(new java.awt.BorderLayout(5, 5));
        
        javax.swing.JScrollPane scrollDueSoon = new javax.swing.JScrollPane();
        tblDueSoon = new javax.swing.JTable();
        tblDueSoon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Mã Thẻ", "Tên Độc Giả", "SĐT", "Email", "Tên Sách", "Hạn Trả", "Còn (ngày)" }
        ) {
            boolean[] canEdit = new boolean [] { false, false, false, false, false, false, false };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDueSoon.setRowHeight(25);
        tblDueSoon.getTableHeader().setReorderingAllowed(false);
        scrollDueSoon.setViewportView(tblDueSoon);
        
        btnRemindDueSoon = new javax.swing.JButton("📧 Nhắc nhở độc giả");
        btnRemindDueSoon.setBackground(new java.awt.Color(241, 196, 15));
        btnRemindDueSoon.setForeground(java.awt.Color.WHITE);
        btnRemindDueSoon.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnRemindDueSoon.setFocusPainted(false);
        
        javax.swing.JPanel pnlDueSoonBtn = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pnlDueSoonBtn.add(btnRemindDueSoon);
        
        pnlDueSoon.add(scrollDueSoon, java.awt.BorderLayout.CENTER);
        pnlDueSoon.add(pnlDueSoonBtn, java.awt.BorderLayout.SOUTH);
        
        tabbedPane.addTab("⚠️ Sắp Hết Hạn (3 ngày)", pnlDueSoon);
        
        // Tab 3: Unpaid Penalties
        javax.swing.JPanel pnlUnpaid = new javax.swing.JPanel();
        pnlUnpaid.setLayout(new java.awt.BorderLayout(5, 5));
        
        javax.swing.JScrollPane scrollUnpaid = new javax.swing.JScrollPane();
        tblUnpaidPenalty = new javax.swing.JTable();
        tblUnpaidPenalty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Mã Thẻ", "Tên Độc Giả", "SĐT", "Lý Do", "Số Tiền", "Ngày Phạt" }
        ) {
            boolean[] canEdit = new boolean [] { false, false, false, false, false, false };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUnpaidPenalty.setRowHeight(25);
        tblUnpaidPenalty.getTableHeader().setReorderingAllowed(false);
        scrollUnpaid.setViewportView(tblUnpaidPenalty);
        
        pnlUnpaid.add(scrollUnpaid, java.awt.BorderLayout.CENTER);
        
        tabbedPane.addTab("💰 Phạt Chưa Đóng", pnlUnpaid);
        
        // --- REFRESH BUTTON ---
        javax.swing.JPanel pnlBottom = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        btnRefresh = new javax.swing.JButton("🔄 Làm mới");
        btnRefresh.setBackground(new java.awt.Color(52, 152, 219));
        btnRefresh.setForeground(java.awt.Color.WHITE);
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnRefresh.setFocusPainted(false);
        pnlBottom.add(btnRefresh);
        
        // --- LAYOUT ---
        setLayout(new java.awt.BorderLayout(10, 10));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Welcome Panel
        pnlWelcome.setLayout(new java.awt.BorderLayout(10, 5));
        pnlWelcome.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        
        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24));
        lblWelcome.setForeground(new java.awt.Color(52, 73, 94));
        lblWelcome.setText("👋 Chào mừng đến với Hệ Thống Quản Lý Thư Viện");
        
        lblDateTime.setFont(new java.awt.Font("Segoe UI", 0, 14));
        lblDateTime.setForeground(new java.awt.Color(127, 140, 141));
        lblDateTime.setText("📅 " + new java.text.SimpleDateFormat("EEEE, dd/MM/yyyy HH:mm:ss").format(new java.util.Date()));
        
        pnlWelcome.add(lblWelcome, java.awt.BorderLayout.NORTH);
        pnlWelcome.add(lblDateTime, java.awt.BorderLayout.CENTER);
        
        add(pnlWelcome, java.awt.BorderLayout.NORTH);
        
        // Stats Panel
        pnlStats.setLayout(new java.awt.GridLayout(1, 4, 15, 0));
        pnlStats.setPreferredSize(new java.awt.Dimension(0, 120));
        pnlStats.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 15, 0));
        
        pnlStats.add(pnlCard1);
        pnlStats.add(pnlCard2);
        pnlStats.add(pnlCard3);
        pnlStats.add(pnlCard4);
        
        // Center Panel
        javax.swing.JPanel pnlCenter = new javax.swing.JPanel(new java.awt.BorderLayout(0, 10));
        pnlCenter.add(pnlStats, java.awt.BorderLayout.NORTH);
        pnlCenter.add(tabbedPane, java.awt.BorderLayout.CENTER);
        pnlCenter.add(pnlBottom, java.awt.BorderLayout.SOUTH);
        
        add(pnlCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Helper methods
    private javax.swing.JPanel createStatCard(String title, java.awt.Color color) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setBackground(color);
        panel.setLayout(new java.awt.BorderLayout());
        panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(color.darker(), 2),
            javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));
        
        javax.swing.JLabel lblTitle = new javax.swing.JLabel(title);
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 13));
        lblTitle.setForeground(java.awt.Color.WHITE);
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        panel.add(lblTitle, java.awt.BorderLayout.NORTH);
        return panel;
    }
    
    private void styleValueLabel(javax.swing.JLabel label) {
        label.setFont(new java.awt.Font("Segoe UI", 1, 32));
        label.setForeground(java.awt.Color.WHITE);
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    // Variables
    private javax.swing.JButton btnCallOverdue;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemindDueSoon;
    private javax.swing.JLabel lblBorrowingCount;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblDueSoonCount;
    private javax.swing.JLabel lblOverdueCount;
    private javax.swing.JLabel lblUnpaidPenalty;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblDueSoon;
    private javax.swing.JTable tblOverdue;
    private javax.swing.JTable tblUnpaidPenalty;
    // End Variables

    // Getters
    public javax.swing.JButton getBtnCallOverdue() { return btnCallOverdue; }
    public javax.swing.JButton getBtnRefresh() { return btnRefresh; }
    public javax.swing.JButton getBtnRemindDueSoon() { return btnRemindDueSoon; }
    public javax.swing.JLabel getLblBorrowingCount() { return lblBorrowingCount; }
    public javax.swing.JLabel getLblDateTime() { return lblDateTime; }
    public javax.swing.JLabel getLblDueSoonCount() { return lblDueSoonCount; }
    public javax.swing.JLabel getLblOverdueCount() { return lblOverdueCount; }
    public javax.swing.JLabel getLblUnpaidPenalty() { return lblUnpaidPenalty; }
    public javax.swing.JLabel getLblWelcome() { return lblWelcome; }
    public javax.swing.JTable getTblDueSoon() { return tblDueSoon; }
    public javax.swing.JTable getTblOverdue() { return tblOverdue; }
    public javax.swing.JTable getTblUnpaidPenalty() { return tblUnpaidPenalty; }
}
