/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MainController;

/**
 *
 * @author ASUS
 */
public class MainForm extends javax.swing.JFrame {

    private MainController controller;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        controller = new MainController(this);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        // Init components
        javax.swing.JPanel pnlSide = new javax.swing.JPanel();
        javax.swing.JLabel lblTitle = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnReader = new javax.swing.JButton();
        btnBorrow = new javax.swing.JButton();
        btnPenalty = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnAuditLog = new javax.swing.JButton();
        
        javax.swing.JPanel pnlHeader = new javax.swing.JPanel();
        lblUserInfo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        
        pnlDesktop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel(); // Placeholder, might not be needed

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");
        setPreferredSize(new java.awt.Dimension(1280, 720));

        // --- LAYOUT SETUP ---
        getContentPane().setLayout(new java.awt.BorderLayout());

        // --- SIDEBAR (WEST) ---
        pnlSide.setBackground(new java.awt.Color(44, 62, 80)); // Dark Blue
        pnlSide.setPreferredSize(new java.awt.Dimension(220, 100));
        pnlSide.setLayout(new java.awt.GridLayout(13, 1, 0, 5));
        pnlSide.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("THƯ VIỆN");
        pnlSide.add(lblTitle);

        // Separator/Spacer could be added here but GridLayout makes it tricky. 
        // We will just add buttons directly.
        
        // Helper to style buttons
        java.awt.Font btnFont = new java.awt.Font("Segoe UI", 0, 14);
        java.awt.Color txtColor = new java.awt.Color(255, 255, 255);
        java.awt.Color bgColor = new java.awt.Color(44, 62, 80);

        // BTN HOME
        btnHome.setBackground(bgColor);
        btnHome.setFont(btnFont);
        btnHome.setForeground(txtColor);
        btnHome.setText("TRANG CHỦ");
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setIconTextGap(15);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlSide.add(btnHome);

        // BTN BOOK
        btnBook.setBackground(bgColor);
        btnBook.setFont(btnFont);
        btnBook.setForeground(txtColor);
        btnBook.setText("QUẢN LÝ SÁCH");
        btnBook.setBorderPainted(false);
        btnBook.setFocusPainted(false);
        btnBook.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBook.setIconTextGap(15);
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        pnlSide.add(btnBook);

        // BTN READER
        btnReader.setBackground(bgColor);
        btnReader.setFont(btnFont);
        btnReader.setForeground(txtColor);
        btnReader.setText("QUẢN LÝ ĐỘC GIẢ");
        btnReader.setBorderPainted(false);
        btnReader.setFocusPainted(false);
        btnReader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReader.setIconTextGap(15);
        btnReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaderActionPerformed(evt);
            }
        });
        pnlSide.add(btnReader);

        // BTN BORROW
        btnBorrow.setBackground(bgColor);
        btnBorrow.setFont(btnFont);
        btnBorrow.setForeground(txtColor);
        btnBorrow.setText("MƯỢN - TRẢ");
        btnBorrow.setBorderPainted(false);
        btnBorrow.setFocusPainted(false);
        btnBorrow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBorrow.setIconTextGap(15);
        btnBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowActionPerformed(evt);
            }
        });
        pnlSide.add(btnBorrow);

        // BTN PENALTY
        btnPenalty.setBackground(bgColor);
        btnPenalty.setFont(btnFont);
        btnPenalty.setForeground(txtColor);
        btnPenalty.setText("VI PHẠM");
        btnPenalty.setBorderPainted(false);
        btnPenalty.setFocusPainted(false);
        btnPenalty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPenalty.setIconTextGap(15);
        btnPenalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenaltyActionPerformed(evt);
            }
        });
        pnlSide.add(btnPenalty);

        // BTN REPORT
        btnReport.setBackground(bgColor);
        btnReport.setFont(btnFont);
        btnReport.setForeground(txtColor);
        btnReport.setText("BÁO CÁO");
        btnReport.setBorderPainted(false);
        btnReport.setFocusPainted(false);
        btnReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReport.setIconTextGap(15);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        pnlSide.add(btnReport);

        // BTN CATEGORY
        btnCategory.setBackground(bgColor);
        btnCategory.setFont(btnFont);
        btnCategory.setForeground(txtColor);
        btnCategory.setText("THỂ LOẠI");
        btnCategory.setBorderPainted(false);
        btnCategory.setFocusPainted(false);
        btnCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategory.setIconTextGap(15);
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });
        pnlSide.add(btnCategory);

        // BTN USER
        btnUser.setBackground(bgColor);
        btnUser.setFont(btnFont);
        btnUser.setForeground(txtColor);
        btnUser.setText("NGƯỜI DÙNG");
        btnUser.setBorderPainted(false);
        btnUser.setFocusPainted(false);
        btnUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUser.setIconTextGap(15);
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        pnlSide.add(btnUser);

        // BTN AUDIT LOG
        btnAuditLog.setBackground(bgColor);
        btnAuditLog.setFont(btnFont);
        btnAuditLog.setForeground(txtColor);
        btnAuditLog.setText("NHẬT KÝ");
        btnAuditLog.setBorderPainted(false);
        btnAuditLog.setFocusPainted(false);
        btnAuditLog.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAuditLog.setIconTextGap(15);
        btnAuditLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditLogActionPerformed(evt);
            }
        });
        pnlSide.add(btnAuditLog);

        getContentPane().add(pnlSide, java.awt.BorderLayout.WEST);

        // --- HEADER (NORTH) ---
        pnlHeader.setBackground(new java.awt.Color(236, 240, 241));
        pnlHeader.setPreferredSize(new java.awt.Dimension(800, 60));
        pnlHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 15));
        pnlHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblUserInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserInfo.setForeground(new java.awt.Color(51, 51, 51));
        lblUserInfo.setText("Xin chào: Admin");
        pnlHeader.add(lblUserInfo);

        btnLogout.setBackground(new java.awt.Color(231, 76, 60));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("ĐĂNG XUẤT");
        btnLogout.setFocusPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlHeader.add(btnLogout);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.NORTH);

        // --- CENTER DESKTOP ---
        pnlDesktop.setBackground(new java.awt.Color(255, 255, 255));
        pnlDesktop.setLayout(new java.awt.CardLayout());
        
        // Add a default welcome / dashboard panel
        javax.swing.JPanel pnlWelcome = new javax.swing.JPanel();
        pnlWelcome.setBackground(new java.awt.Color(255, 255, 255));
        pnlWelcome.setLayout(new java.awt.GridBagLayout());
        javax.swing.JLabel lblWelcome = new javax.swing.JLabel("CHÀO MỪNG ĐẾN VỚI HỆ THỐNG QUẢN LÝ THƯ VIỆN");
        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24));
        lblWelcome.setForeground(new java.awt.Color(204, 204, 204));
        pnlWelcome.add(lblWelcome);
        pnlDesktop.add(pnlWelcome, "card0");

        getContentPane().add(pnlDesktop, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReaderActionPerformed

    private void btnPenaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenaltyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPenaltyActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrowActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnAuditLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAuditLogActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuditLog;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnBorrow;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPenalty;
    private javax.swing.JButton btnReader;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUserInfo;
    private javax.swing.JPanel pnlDesktop;
    // End of variables declaration//GEN-END:variables
    
    // C�c Getter n�y b? comment d? ch?y du?c Design View.
    // Sau khi thi?t k? giao di?n xong (drag-drop c�c n�t Menu...), b?n h�y d?i t�n bi?n (Change Variable Name)
    // cho c�c n�t b?m gi?ng nhu b�n du?i (btnBook, btnReader...), r?i uncomment do?n code n�y.
    
    
    public javax.swing.JButton getBtnBook() {
        return btnBook;
    }

    public javax.swing.JButton getBtnBorrow() {
        return btnBorrow;
    }

    public javax.swing.JButton getBtnHome() {
        return btnHome;
    }

    public javax.swing.JButton getBtnLogout() {
        return btnLogout;
    }

    public javax.swing.JButton getBtnPenalty() {
        return btnPenalty;
    }

    public javax.swing.JButton getBtnReader() {
        return btnReader;
    }

    public javax.swing.JButton getBtnReport() {
        return btnReport;
    }

    public javax.swing.JLabel getLblUserInfo() {
        return lblUserInfo;
    }
    
    public javax.swing.JPanel getPnlDesktop() {
        return pnlDesktop;
    }
    
    // Getter methods for new buttons (if they exist in the form)
    // If not added in NetBeans Design view, these will return null safely
    public javax.swing.JButton getBtnUser() {
        return btnUser;
    }
    
    public javax.swing.JButton getBtnChangePassword() {
        // Return null if button doesn't exist yet - controller will handle
        return null; // TODO: Add btnChangePassword to MainForm.form in NetBeans
    }
    
    public javax.swing.JButton getBtnCategory() {
        return btnCategory;
    }
    
    public javax.swing.JButton getBtnAuditLog() {
        return btnAuditLog;
    }
    
}
