/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ReportController;

/**
 *
 * @author ASUS
 */
public class ReportForm extends javax.swing.JPanel {

    private ReportController controller;

    /**
     * Creates new form ReportForm
     */
    public ReportForm() {
        initComponents();
        controller = new ReportController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        
        // --- Components ---
        javax.swing.JPanel pnlStats = new javax.swing.JPanel();
        javax.swing.JPanel pnlContent = new javax.swing.JPanel();
        
        // Stat Cards (using Panels with Borders)
        javax.swing.JPanel pnlCard1 = createStatCard("TỔNG SỐ SÁCH", new java.awt.Color(52, 152, 219));
        lblTotalBooks = new javax.swing.JLabel("0");
        
        javax.swing.JPanel pnlCard2 = createStatCard("ĐỘC GIẢ", new java.awt.Color(46, 204, 113));
        lblTotalReaders = new javax.swing.JLabel("0");
        
        javax.swing.JPanel pnlCard3 = createStatCard("ĐANG MƯỢN", new java.awt.Color(241, 196, 15));
        lblBorrowed = new javax.swing.JLabel("0");
        
        javax.swing.JPanel pnlCard4 = createStatCard("QUÁ HẠN", new java.awt.Color(231, 76, 60));
        lblOverdue = new javax.swing.JLabel("0");
        
        // Add labels to cards
        styleValueLabel(lblTotalBooks); pnlCard1.add(lblTotalBooks);
        styleValueLabel(lblTotalReaders); pnlCard2.add(lblTotalReaders);
        styleValueLabel(lblBorrowed); pnlCard3.add(lblBorrowed);
        styleValueLabel(lblOverdue); pnlCard4.add(lblOverdue);

        // Tabbed Pane for Tables
        javax.swing.JTabbedPane tabbedPane = new javax.swing.JTabbedPane();
        
        javax.swing.JScrollPane scrollRecent = new javax.swing.JScrollPane();
        tblRecent = new javax.swing.JTable() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        
        javax.swing.JScrollPane scrollTop = new javax.swing.JScrollPane();
        tblTopReaders = new javax.swing.JTable() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        
        javax.swing.JScrollPane scrollBorrowing = new javax.swing.JScrollPane();
        tblBorrowing = new javax.swing.JTable() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        btnRefresh = new javax.swing.JButton("Cập nhật dữ liệu");
        btnExportRecent = new javax.swing.JButton("Xuất Excel");
        btnExportTop = new javax.swing.JButton("Xuất Excel");
        btnExportBorrowing = new javax.swing.JButton("Xuất Excel");

        // --- LAYOUT ---
        setLayout(new java.awt.BorderLayout(10, 10));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // 1. STATS PANEL (Top)
        pnlStats.setLayout(new java.awt.GridLayout(1, 4, 15, 0));
        pnlStats.setPreferredSize(new java.awt.Dimension(0, 120));
        
        pnlStats.add(pnlCard1);
        pnlStats.add(pnlCard2);
        pnlStats.add(pnlCard3);
        pnlStats.add(pnlCard4);
        
        add(pnlStats, java.awt.BorderLayout.NORTH);

        // 2. CONTENT PANEL (Center)
        pnlContent.setLayout(new java.awt.BorderLayout(0, 10));
        
        // Tables Setup
        // Tab 1: Recent Activity
        javax.swing.JPanel pnlRecentTab = new javax.swing.JPanel(new java.awt.BorderLayout(5, 5));
        tblRecent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Mã phiếu", "Người mượn", "Ngày mượn", "Hạn trả", "Trạng thái" }
        ));
        scrollRecent.setViewportView(tblRecent);
        pnlRecentTab.add(scrollRecent, java.awt.BorderLayout.CENTER);
        javax.swing.JPanel pnlRecentBtn = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        btnExportRecent.setBackground(new java.awt.Color(39, 174, 96));
        btnExportRecent.setForeground(java.awt.Color.WHITE);
        btnExportRecent.setFocusPainted(false);
        pnlRecentBtn.add(btnExportRecent);
        pnlRecentTab.add(pnlRecentBtn, java.awt.BorderLayout.SOUTH);
        tabbedPane.addTab("Hoạt động gần đây", pnlRecentTab);
        
        // Tab 2: Top Readers
        javax.swing.JPanel pnlTopTab = new javax.swing.JPanel(new java.awt.BorderLayout(5, 5));
        tblTopReaders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Xếp hạng", "Tên độc giả", "Số lần mượn" }
        ));
        scrollTop.setViewportView(tblTopReaders);
        pnlTopTab.add(scrollTop, java.awt.BorderLayout.CENTER);
        javax.swing.JPanel pnlTopBtn = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        btnExportTop.setBackground(new java.awt.Color(39, 174, 96));
        btnExportTop.setForeground(java.awt.Color.WHITE);
        btnExportTop.setFocusPainted(false);
        pnlTopBtn.add(btnExportTop);
        pnlTopTab.add(pnlTopBtn, java.awt.BorderLayout.SOUTH);
        tabbedPane.addTab("Độc giả tích cực", pnlTopTab);
        
        // Tab 3: Borrowing List
        javax.swing.JPanel pnlBorrowingTab = new javax.swing.JPanel(new java.awt.BorderLayout(5, 5));
        tblBorrowing = new javax.swing.JTable();
        tblBorrowing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Mã thẻ", "Tên ĐG", "Tên Sách", "Ngày Mượn", "Hạn Trả" }
        ));
        scrollBorrowing.setViewportView(tblBorrowing);
        pnlBorrowingTab.add(scrollBorrowing, java.awt.BorderLayout.CENTER);
        javax.swing.JPanel pnlBorrowingBtn = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        btnExportBorrowing.setBackground(new java.awt.Color(39, 174, 96));
        btnExportBorrowing.setForeground(java.awt.Color.WHITE);
        btnExportBorrowing.setFocusPainted(false);
        pnlBorrowingBtn.add(btnExportBorrowing);
        pnlBorrowingTab.add(pnlBorrowingBtn, java.awt.BorderLayout.SOUTH);
        tabbedPane.addTab("Danh sách đang mượn", pnlBorrowingTab);
        
        pnlContent.add(tabbedPane, java.awt.BorderLayout.CENTER);
        
        // Refresh Button Panel
        javax.swing.JPanel pnlBtn = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        btnRefresh.setBackground(new java.awt.Color(52, 152, 219));
        btnRefresh.setForeground(java.awt.Color.WHITE);
        btnRefresh.setFocusPainted(false);
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12));
        pnlBtn.add(btnRefresh);
        pnlContent.add(pnlBtn, java.awt.BorderLayout.SOUTH);

        add(pnlContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>

    // Helper to create styled cards
    private javax.swing.JPanel createStatCard(String title, java.awt.Color color) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setBackground(color);
        panel.setLayout(new java.awt.BorderLayout());
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        javax.swing.JLabel lblTitle = new javax.swing.JLabel(title);
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lblTitle.setForeground(java.awt.Color.WHITE);
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        panel.add(lblTitle, java.awt.BorderLayout.NORTH);
        return panel;
    }
    
    private void styleValueLabel(javax.swing.JLabel label) {
        label.setFont(new java.awt.Font("Segoe UI", 1, 36));
        label.setForeground(java.awt.Color.WHITE);
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    // Variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnExportRecent;
    private javax.swing.JButton btnExportTop;
    private javax.swing.JButton btnExportBorrowing;
    private javax.swing.JLabel lblBorrowed;
    private javax.swing.JLabel lblOverdue;
    private javax.swing.JLabel lblTotalBooks;
    private javax.swing.JLabel lblTotalReaders;
    private javax.swing.JTable tblRecent;
    private javax.swing.JTable tblTopReaders;
    private javax.swing.JTable tblBorrowing;
    // End Variables

    // Getters
    public javax.swing.JButton getBtnRefresh() { return btnRefresh; }
    public javax.swing.JButton getBtnExportRecent() { return btnExportRecent; }
    public javax.swing.JButton getBtnExportTop() { return btnExportTop; }
    public javax.swing.JButton getBtnExportBorrowing() { return btnExportBorrowing; }
    public javax.swing.JLabel getLblBorrowed() { return lblBorrowed; }
    public javax.swing.JLabel getLblOverdue() { return lblOverdue; }
    public javax.swing.JLabel getLblTotalBooks() { return lblTotalBooks; }
    public javax.swing.JLabel getLblTotalReaders() { return lblTotalReaders; }
    public javax.swing.JTable getTblRecent() { return tblRecent; }
    public javax.swing.JTable getTblTopReaders() { return tblTopReaders; }
    public javax.swing.JTable getTblBorrowing() { return tblBorrowing; }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
